/**
 *
 *  NodeMetadata.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "NodeMetadata.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::myapp;

const std::string NodeMetadata::Cols::_metadata_id = "\"metadata_id\"";
const std::string NodeMetadata::Cols::_node_id = "\"node_id\"";
const std::string NodeMetadata::Cols::_key_name = "\"key_name\"";
const std::string NodeMetadata::Cols::_value_text = "\"value_text\"";
const std::string NodeMetadata::Cols::_value_int = "\"value_int\"";
const std::string NodeMetadata::Cols::_value_numeric = "\"value_numeric\"";
const std::string NodeMetadata::Cols::_value_boolean = "\"value_boolean\"";
const std::string NodeMetadata::Cols::_value_date = "\"value_date\"";
const std::string NodeMetadata::Cols::_value_timestamp = "\"value_timestamp\"";
const std::string NodeMetadata::Cols::_value_json = "\"value_json\"";
const std::string NodeMetadata::Cols::_value_uuid = "\"value_uuid\"";
const std::string NodeMetadata::Cols::_value_bytea = "\"value_bytea\"";
const std::string NodeMetadata::primaryKeyName = "metadata_id";
const bool NodeMetadata::hasPrimaryKey = true;
const std::string NodeMetadata::tableName = "\"node_metadata\"";

const std::vector<typename NodeMetadata::MetaData> NodeMetadata::metaData_={
{"metadata_id","int32_t","integer",4,1,1,1},
{"node_id","int32_t","integer",4,0,0,1},
{"key_name","std::string","text",0,0,0,1},
{"value_text","std::string","text",0,0,0,0},
{"value_int","int32_t","integer",4,0,0,0},
{"value_numeric","std::string","numeric",0,0,0,0},
{"value_boolean","bool","boolean",1,0,0,0},
{"value_date","::trantor::Date","date",0,0,0,0},
{"value_timestamp","::trantor::Date","timestamp without time zone",0,0,0,0},
{"value_json","std::string","jsonb",0,0,0,0},
{"value_uuid","std::string","uuid",0,0,0,0},
{"value_bytea","std::vector<char>","bytea",0,0,0,0}
};
const std::string &NodeMetadata::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
NodeMetadata::NodeMetadata(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["metadata_id"].isNull())
        {
            metadataId_=std::make_shared<int32_t>(r["metadata_id"].as<int32_t>());
        }
        if(!r["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r["node_id"].as<int32_t>());
        }
        if(!r["key_name"].isNull())
        {
            keyName_=std::make_shared<std::string>(r["key_name"].as<std::string>());
        }
        if(!r["value_text"].isNull())
        {
            valueText_=std::make_shared<std::string>(r["value_text"].as<std::string>());
        }
        if(!r["value_int"].isNull())
        {
            valueInt_=std::make_shared<int32_t>(r["value_int"].as<int32_t>());
        }
        if(!r["value_numeric"].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(r["value_numeric"].as<std::string>());
        }
        if(!r["value_boolean"].isNull())
        {
            valueBoolean_=std::make_shared<bool>(r["value_boolean"].as<bool>());
        }
        if(!r["value_date"].isNull())
        {
            auto daysStr = r["value_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["value_timestamp"].isNull())
        {
            auto timeStr = r["value_timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["value_json"].isNull())
        {
            valueJson_=std::make_shared<std::string>(r["value_json"].as<std::string>());
        }
        if(!r["value_uuid"].isNull())
        {
            valueUuid_=std::make_shared<std::string>(r["value_uuid"].as<std::string>());
        }
        if(!r["value_bytea"].isNull())
        {
            auto str = r["value_bytea"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 12 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            metadataId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            keyName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            valueText_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            valueInt_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            valueBoolean_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            valueJson_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            valueUuid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
    }

}

NodeMetadata::NodeMetadata(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            metadataId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            keyName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            valueText_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            valueInt_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            valueBoolean_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            valueJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            valueUuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto str = pJson[pMasqueradingVector[11]].asString();
            valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

NodeMetadata::NodeMetadata(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("metadata_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["metadata_id"].isNull())
        {
            metadataId_=std::make_shared<int32_t>((int32_t)pJson["metadata_id"].asInt64());
        }
    }
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("key_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["key_name"].isNull())
        {
            keyName_=std::make_shared<std::string>(pJson["key_name"].asString());
        }
    }
    if(pJson.isMember("value_text"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["value_text"].isNull())
        {
            valueText_=std::make_shared<std::string>(pJson["value_text"].asString());
        }
    }
    if(pJson.isMember("value_int"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["value_int"].isNull())
        {
            valueInt_=std::make_shared<int32_t>((int32_t)pJson["value_int"].asInt64());
        }
    }
    if(pJson.isMember("value_numeric"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["value_numeric"].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(pJson["value_numeric"].asString());
        }
    }
    if(pJson.isMember("value_boolean"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["value_boolean"].isNull())
        {
            valueBoolean_=std::make_shared<bool>(pJson["value_boolean"].asBool());
        }
    }
    if(pJson.isMember("value_date"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["value_date"].isNull())
        {
            auto daysStr = pJson["value_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("value_timestamp"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["value_timestamp"].isNull())
        {
            auto timeStr = pJson["value_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("value_json"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["value_json"].isNull())
        {
            valueJson_=std::make_shared<std::string>(pJson["value_json"].asString());
        }
    }
    if(pJson.isMember("value_uuid"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["value_uuid"].isNull())
        {
            valueUuid_=std::make_shared<std::string>(pJson["value_uuid"].asString());
        }
    }
    if(pJson.isMember("value_bytea"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["value_bytea"].isNull())
        {
            auto str = pJson["value_bytea"].asString();
            valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

void NodeMetadata::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            metadataId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            keyName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            valueText_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            valueInt_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            valueBoolean_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            valueJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            valueUuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto str = pJson[pMasqueradingVector[11]].asString();
            valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

void NodeMetadata::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("metadata_id"))
    {
        if(!pJson["metadata_id"].isNull())
        {
            metadataId_=std::make_shared<int32_t>((int32_t)pJson["metadata_id"].asInt64());
        }
    }
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("key_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["key_name"].isNull())
        {
            keyName_=std::make_shared<std::string>(pJson["key_name"].asString());
        }
    }
    if(pJson.isMember("value_text"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["value_text"].isNull())
        {
            valueText_=std::make_shared<std::string>(pJson["value_text"].asString());
        }
    }
    if(pJson.isMember("value_int"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["value_int"].isNull())
        {
            valueInt_=std::make_shared<int32_t>((int32_t)pJson["value_int"].asInt64());
        }
    }
    if(pJson.isMember("value_numeric"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["value_numeric"].isNull())
        {
            valueNumeric_=std::make_shared<std::string>(pJson["value_numeric"].asString());
        }
    }
    if(pJson.isMember("value_boolean"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["value_boolean"].isNull())
        {
            valueBoolean_=std::make_shared<bool>(pJson["value_boolean"].asBool());
        }
    }
    if(pJson.isMember("value_date"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["value_date"].isNull())
        {
            auto daysStr = pJson["value_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            valueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("value_timestamp"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["value_timestamp"].isNull())
        {
            auto timeStr = pJson["value_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                valueTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("value_json"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["value_json"].isNull())
        {
            valueJson_=std::make_shared<std::string>(pJson["value_json"].asString());
        }
    }
    if(pJson.isMember("value_uuid"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["value_uuid"].isNull())
        {
            valueUuid_=std::make_shared<std::string>(pJson["value_uuid"].asString());
        }
    }
    if(pJson.isMember("value_bytea"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["value_bytea"].isNull())
        {
            auto str = pJson["value_bytea"].asString();
            valueBytea_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

const int32_t &NodeMetadata::getValueOfMetadataId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(metadataId_)
        return *metadataId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &NodeMetadata::getMetadataId() const noexcept
{
    return metadataId_;
}
void NodeMetadata::setMetadataId(const int32_t &pMetadataId) noexcept
{
    metadataId_ = std::make_shared<int32_t>(pMetadataId);
    dirtyFlag_[0] = true;
}
const typename NodeMetadata::PrimaryKeyType & NodeMetadata::getPrimaryKey() const
{
    assert(metadataId_);
    return *metadataId_;
}

const int32_t &NodeMetadata::getValueOfNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nodeId_)
        return *nodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &NodeMetadata::getNodeId() const noexcept
{
    return nodeId_;
}
void NodeMetadata::setNodeId(const int32_t &pNodeId) noexcept
{
    nodeId_ = std::make_shared<int32_t>(pNodeId);
    dirtyFlag_[1] = true;
}

const std::string &NodeMetadata::getValueOfKeyName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(keyName_)
        return *keyName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NodeMetadata::getKeyName() const noexcept
{
    return keyName_;
}
void NodeMetadata::setKeyName(const std::string &pKeyName) noexcept
{
    keyName_ = std::make_shared<std::string>(pKeyName);
    dirtyFlag_[2] = true;
}
void NodeMetadata::setKeyName(std::string &&pKeyName) noexcept
{
    keyName_ = std::make_shared<std::string>(std::move(pKeyName));
    dirtyFlag_[2] = true;
}

const std::string &NodeMetadata::getValueOfValueText() const noexcept
{
    static const std::string defaultValue = std::string();
    if(valueText_)
        return *valueText_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NodeMetadata::getValueText() const noexcept
{
    return valueText_;
}
void NodeMetadata::setValueText(const std::string &pValueText) noexcept
{
    valueText_ = std::make_shared<std::string>(pValueText);
    dirtyFlag_[3] = true;
}
void NodeMetadata::setValueText(std::string &&pValueText) noexcept
{
    valueText_ = std::make_shared<std::string>(std::move(pValueText));
    dirtyFlag_[3] = true;
}
void NodeMetadata::setValueTextToNull() noexcept
{
    valueText_.reset();
    dirtyFlag_[3] = true;
}

const int32_t &NodeMetadata::getValueOfValueInt() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(valueInt_)
        return *valueInt_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &NodeMetadata::getValueInt() const noexcept
{
    return valueInt_;
}
void NodeMetadata::setValueInt(const int32_t &pValueInt) noexcept
{
    valueInt_ = std::make_shared<int32_t>(pValueInt);
    dirtyFlag_[4] = true;
}
void NodeMetadata::setValueIntToNull() noexcept
{
    valueInt_.reset();
    dirtyFlag_[4] = true;
}

const std::string &NodeMetadata::getValueOfValueNumeric() const noexcept
{
    static const std::string defaultValue = std::string();
    if(valueNumeric_)
        return *valueNumeric_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NodeMetadata::getValueNumeric() const noexcept
{
    return valueNumeric_;
}
void NodeMetadata::setValueNumeric(const std::string &pValueNumeric) noexcept
{
    valueNumeric_ = std::make_shared<std::string>(pValueNumeric);
    dirtyFlag_[5] = true;
}
void NodeMetadata::setValueNumeric(std::string &&pValueNumeric) noexcept
{
    valueNumeric_ = std::make_shared<std::string>(std::move(pValueNumeric));
    dirtyFlag_[5] = true;
}
void NodeMetadata::setValueNumericToNull() noexcept
{
    valueNumeric_.reset();
    dirtyFlag_[5] = true;
}

const bool &NodeMetadata::getValueOfValueBoolean() const noexcept
{
    static const bool defaultValue = bool();
    if(valueBoolean_)
        return *valueBoolean_;
    return defaultValue;
}
const std::shared_ptr<bool> &NodeMetadata::getValueBoolean() const noexcept
{
    return valueBoolean_;
}
void NodeMetadata::setValueBoolean(const bool &pValueBoolean) noexcept
{
    valueBoolean_ = std::make_shared<bool>(pValueBoolean);
    dirtyFlag_[6] = true;
}
void NodeMetadata::setValueBooleanToNull() noexcept
{
    valueBoolean_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &NodeMetadata::getValueOfValueDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(valueDate_)
        return *valueDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &NodeMetadata::getValueDate() const noexcept
{
    return valueDate_;
}
void NodeMetadata::setValueDate(const ::trantor::Date &pValueDate) noexcept
{
    valueDate_ = std::make_shared<::trantor::Date>(pValueDate.roundDay());
    dirtyFlag_[7] = true;
}
void NodeMetadata::setValueDateToNull() noexcept
{
    valueDate_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &NodeMetadata::getValueOfValueTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(valueTimestamp_)
        return *valueTimestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &NodeMetadata::getValueTimestamp() const noexcept
{
    return valueTimestamp_;
}
void NodeMetadata::setValueTimestamp(const ::trantor::Date &pValueTimestamp) noexcept
{
    valueTimestamp_ = std::make_shared<::trantor::Date>(pValueTimestamp);
    dirtyFlag_[8] = true;
}
void NodeMetadata::setValueTimestampToNull() noexcept
{
    valueTimestamp_.reset();
    dirtyFlag_[8] = true;
}

const std::string &NodeMetadata::getValueOfValueJson() const noexcept
{
    static const std::string defaultValue = std::string();
    if(valueJson_)
        return *valueJson_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NodeMetadata::getValueJson() const noexcept
{
    return valueJson_;
}
void NodeMetadata::setValueJson(const std::string &pValueJson) noexcept
{
    valueJson_ = std::make_shared<std::string>(pValueJson);
    dirtyFlag_[9] = true;
}
void NodeMetadata::setValueJson(std::string &&pValueJson) noexcept
{
    valueJson_ = std::make_shared<std::string>(std::move(pValueJson));
    dirtyFlag_[9] = true;
}
void NodeMetadata::setValueJsonToNull() noexcept
{
    valueJson_.reset();
    dirtyFlag_[9] = true;
}

const std::string &NodeMetadata::getValueOfValueUuid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(valueUuid_)
        return *valueUuid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NodeMetadata::getValueUuid() const noexcept
{
    return valueUuid_;
}
void NodeMetadata::setValueUuid(const std::string &pValueUuid) noexcept
{
    valueUuid_ = std::make_shared<std::string>(pValueUuid);
    dirtyFlag_[10] = true;
}
void NodeMetadata::setValueUuid(std::string &&pValueUuid) noexcept
{
    valueUuid_ = std::make_shared<std::string>(std::move(pValueUuid));
    dirtyFlag_[10] = true;
}
void NodeMetadata::setValueUuidToNull() noexcept
{
    valueUuid_.reset();
    dirtyFlag_[10] = true;
}

const std::vector<char> &NodeMetadata::getValueOfValueBytea() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(valueBytea_)
        return *valueBytea_;
    return defaultValue;
}
std::string NodeMetadata::getValueOfValueByteaAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(valueBytea_)
        return std::string(valueBytea_->data(),valueBytea_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &NodeMetadata::getValueBytea() const noexcept
{
    return valueBytea_;
}
void NodeMetadata::setValueBytea(const std::vector<char> &pValueBytea) noexcept
{
    valueBytea_ = std::make_shared<std::vector<char>>(pValueBytea);
    dirtyFlag_[11] = true;
}
void NodeMetadata::setValueBytea(const std::string &pValueBytea) noexcept
{
    valueBytea_ = std::make_shared<std::vector<char>>(pValueBytea.c_str(),pValueBytea.c_str()+pValueBytea.length());
    dirtyFlag_[11] = true;
}
void NodeMetadata::setValueByteaToNull() noexcept
{
    valueBytea_.reset();
    dirtyFlag_[11] = true;
}

void NodeMetadata::updateId(const uint64_t id)
{
}

const std::vector<std::string> &NodeMetadata::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "node_id",
        "key_name",
        "value_text",
        "value_int",
        "value_numeric",
        "value_boolean",
        "value_date",
        "value_timestamp",
        "value_json",
        "value_uuid",
        "value_bytea"
    };
    return inCols;
}

void NodeMetadata::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNodeId())
        {
            binder << getValueOfNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getKeyName())
        {
            binder << getValueOfKeyName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getValueText())
        {
            binder << getValueOfValueText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getValueInt())
        {
            binder << getValueOfValueInt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getValueNumeric())
        {
            binder << getValueOfValueNumeric();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getValueBoolean())
        {
            binder << getValueOfValueBoolean();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getValueDate())
        {
            binder << getValueOfValueDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getValueTimestamp())
        {
            binder << getValueOfValueTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getValueJson())
        {
            binder << getValueOfValueJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getValueUuid())
        {
            binder << getValueOfValueUuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getValueBytea())
        {
            binder << getValueOfValueBytea();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> NodeMetadata::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    return ret;
}

void NodeMetadata::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNodeId())
        {
            binder << getValueOfNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getKeyName())
        {
            binder << getValueOfKeyName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getValueText())
        {
            binder << getValueOfValueText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getValueInt())
        {
            binder << getValueOfValueInt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getValueNumeric())
        {
            binder << getValueOfValueNumeric();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getValueBoolean())
        {
            binder << getValueOfValueBoolean();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getValueDate())
        {
            binder << getValueOfValueDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getValueTimestamp())
        {
            binder << getValueOfValueTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getValueJson())
        {
            binder << getValueOfValueJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getValueUuid())
        {
            binder << getValueOfValueUuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getValueBytea())
        {
            binder << getValueOfValueBytea();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value NodeMetadata::toJson() const
{
    Json::Value ret;
    if(getMetadataId())
    {
        ret["metadata_id"]=getValueOfMetadataId();
    }
    else
    {
        ret["metadata_id"]=Json::Value();
    }
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getKeyName())
    {
        ret["key_name"]=getValueOfKeyName();
    }
    else
    {
        ret["key_name"]=Json::Value();
    }
    if(getValueText())
    {
        ret["value_text"]=getValueOfValueText();
    }
    else
    {
        ret["value_text"]=Json::Value();
    }
    if(getValueInt())
    {
        ret["value_int"]=getValueOfValueInt();
    }
    else
    {
        ret["value_int"]=Json::Value();
    }
    if(getValueNumeric())
    {
        ret["value_numeric"]=getValueOfValueNumeric();
    }
    else
    {
        ret["value_numeric"]=Json::Value();
    }
    if(getValueBoolean())
    {
        ret["value_boolean"]=getValueOfValueBoolean();
    }
    else
    {
        ret["value_boolean"]=Json::Value();
    }
    if(getValueDate())
    {
        ret["value_date"]=getValueDate()->toDbStringLocal();
    }
    else
    {
        ret["value_date"]=Json::Value();
    }
    if(getValueTimestamp())
    {
        ret["value_timestamp"]=getValueTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["value_timestamp"]=Json::Value();
    }
    if(getValueJson())
    {
        ret["value_json"]=getValueOfValueJson();
    }
    else
    {
        ret["value_json"]=Json::Value();
    }
    if(getValueUuid())
    {
        ret["value_uuid"]=getValueOfValueUuid();
    }
    else
    {
        ret["value_uuid"]=Json::Value();
    }
    if(getValueBytea())
    {
        ret["value_bytea"]=drogon::utils::base64Encode((const unsigned char *)getValueBytea()->data(),getValueBytea()->size());
    }
    else
    {
        ret["value_bytea"]=Json::Value();
    }
    return ret;
}

Json::Value NodeMetadata::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 12)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getMetadataId())
            {
                ret[pMasqueradingVector[0]]=getValueOfMetadataId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNodeId())
            {
                ret[pMasqueradingVector[1]]=getValueOfNodeId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getKeyName())
            {
                ret[pMasqueradingVector[2]]=getValueOfKeyName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getValueText())
            {
                ret[pMasqueradingVector[3]]=getValueOfValueText();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getValueInt())
            {
                ret[pMasqueradingVector[4]]=getValueOfValueInt();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getValueNumeric())
            {
                ret[pMasqueradingVector[5]]=getValueOfValueNumeric();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getValueBoolean())
            {
                ret[pMasqueradingVector[6]]=getValueOfValueBoolean();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getValueDate())
            {
                ret[pMasqueradingVector[7]]=getValueDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getValueTimestamp())
            {
                ret[pMasqueradingVector[8]]=getValueTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getValueJson())
            {
                ret[pMasqueradingVector[9]]=getValueOfValueJson();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getValueUuid())
            {
                ret[pMasqueradingVector[10]]=getValueOfValueUuid();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getValueBytea())
            {
                ret[pMasqueradingVector[11]]=drogon::utils::base64Encode((const unsigned char *)getValueBytea()->data(),getValueBytea()->size());
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getMetadataId())
    {
        ret["metadata_id"]=getValueOfMetadataId();
    }
    else
    {
        ret["metadata_id"]=Json::Value();
    }
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getKeyName())
    {
        ret["key_name"]=getValueOfKeyName();
    }
    else
    {
        ret["key_name"]=Json::Value();
    }
    if(getValueText())
    {
        ret["value_text"]=getValueOfValueText();
    }
    else
    {
        ret["value_text"]=Json::Value();
    }
    if(getValueInt())
    {
        ret["value_int"]=getValueOfValueInt();
    }
    else
    {
        ret["value_int"]=Json::Value();
    }
    if(getValueNumeric())
    {
        ret["value_numeric"]=getValueOfValueNumeric();
    }
    else
    {
        ret["value_numeric"]=Json::Value();
    }
    if(getValueBoolean())
    {
        ret["value_boolean"]=getValueOfValueBoolean();
    }
    else
    {
        ret["value_boolean"]=Json::Value();
    }
    if(getValueDate())
    {
        ret["value_date"]=getValueDate()->toDbStringLocal();
    }
    else
    {
        ret["value_date"]=Json::Value();
    }
    if(getValueTimestamp())
    {
        ret["value_timestamp"]=getValueTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["value_timestamp"]=Json::Value();
    }
    if(getValueJson())
    {
        ret["value_json"]=getValueOfValueJson();
    }
    else
    {
        ret["value_json"]=Json::Value();
    }
    if(getValueUuid())
    {
        ret["value_uuid"]=getValueOfValueUuid();
    }
    else
    {
        ret["value_uuid"]=Json::Value();
    }
    if(getValueBytea())
    {
        ret["value_bytea"]=drogon::utils::base64Encode((const unsigned char *)getValueBytea()->data(),getValueBytea()->size());
    }
    else
    {
        ret["value_bytea"]=Json::Value();
    }
    return ret;
}

bool NodeMetadata::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("metadata_id"))
    {
        if(!validJsonOfField(0, "metadata_id", pJson["metadata_id"], err, true))
            return false;
    }
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(1, "node_id", pJson["node_id"], err, true))
            return false;
    }
    else
    {
        err="The node_id column cannot be null";
        return false;
    }
    if(pJson.isMember("key_name"))
    {
        if(!validJsonOfField(2, "key_name", pJson["key_name"], err, true))
            return false;
    }
    else
    {
        err="The key_name column cannot be null";
        return false;
    }
    if(pJson.isMember("value_text"))
    {
        if(!validJsonOfField(3, "value_text", pJson["value_text"], err, true))
            return false;
    }
    if(pJson.isMember("value_int"))
    {
        if(!validJsonOfField(4, "value_int", pJson["value_int"], err, true))
            return false;
    }
    if(pJson.isMember("value_numeric"))
    {
        if(!validJsonOfField(5, "value_numeric", pJson["value_numeric"], err, true))
            return false;
    }
    if(pJson.isMember("value_boolean"))
    {
        if(!validJsonOfField(6, "value_boolean", pJson["value_boolean"], err, true))
            return false;
    }
    if(pJson.isMember("value_date"))
    {
        if(!validJsonOfField(7, "value_date", pJson["value_date"], err, true))
            return false;
    }
    if(pJson.isMember("value_timestamp"))
    {
        if(!validJsonOfField(8, "value_timestamp", pJson["value_timestamp"], err, true))
            return false;
    }
    if(pJson.isMember("value_json"))
    {
        if(!validJsonOfField(9, "value_json", pJson["value_json"], err, true))
            return false;
    }
    if(pJson.isMember("value_uuid"))
    {
        if(!validJsonOfField(10, "value_uuid", pJson["value_uuid"], err, true))
            return false;
    }
    if(pJson.isMember("value_bytea"))
    {
        if(!validJsonOfField(11, "value_bytea", pJson["value_bytea"], err, true))
            return false;
    }
    return true;
}
bool NodeMetadata::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NodeMetadata::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("metadata_id"))
    {
        if(!validJsonOfField(0, "metadata_id", pJson["metadata_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(1, "node_id", pJson["node_id"], err, false))
            return false;
    }
    if(pJson.isMember("key_name"))
    {
        if(!validJsonOfField(2, "key_name", pJson["key_name"], err, false))
            return false;
    }
    if(pJson.isMember("value_text"))
    {
        if(!validJsonOfField(3, "value_text", pJson["value_text"], err, false))
            return false;
    }
    if(pJson.isMember("value_int"))
    {
        if(!validJsonOfField(4, "value_int", pJson["value_int"], err, false))
            return false;
    }
    if(pJson.isMember("value_numeric"))
    {
        if(!validJsonOfField(5, "value_numeric", pJson["value_numeric"], err, false))
            return false;
    }
    if(pJson.isMember("value_boolean"))
    {
        if(!validJsonOfField(6, "value_boolean", pJson["value_boolean"], err, false))
            return false;
    }
    if(pJson.isMember("value_date"))
    {
        if(!validJsonOfField(7, "value_date", pJson["value_date"], err, false))
            return false;
    }
    if(pJson.isMember("value_timestamp"))
    {
        if(!validJsonOfField(8, "value_timestamp", pJson["value_timestamp"], err, false))
            return false;
    }
    if(pJson.isMember("value_json"))
    {
        if(!validJsonOfField(9, "value_json", pJson["value_json"], err, false))
            return false;
    }
    if(pJson.isMember("value_uuid"))
    {
        if(!validJsonOfField(10, "value_uuid", pJson["value_uuid"], err, false))
            return false;
    }
    if(pJson.isMember("value_bytea"))
    {
        if(!validJsonOfField(11, "value_bytea", pJson["value_bytea"], err, false))
            return false;
    }
    return true;
}
bool NodeMetadata::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NodeMetadata::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
