/**
 *
 *  NodeMetadata.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace myapp
{

class NodeMetadata
{
  public:
    struct Cols
    {
        static const std::string _metadata_id;
        static const std::string _node_id;
        static const std::string _key_name;
        static const std::string _value_text;
        static const std::string _value_int;
        static const std::string _value_numeric;
        static const std::string _value_boolean;
        static const std::string _value_date;
        static const std::string _value_timestamp;
        static const std::string _value_json;
        static const std::string _value_uuid;
        static const std::string _value_bytea;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit NodeMetadata(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit NodeMetadata(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    NodeMetadata(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    NodeMetadata() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column metadata_id  */
    ///Get the value of the column metadata_id, returns the default value if the column is null
    const int32_t &getValueOfMetadataId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMetadataId() const noexcept;
    ///Set the value of the column metadata_id
    void setMetadataId(const int32_t &pMetadataId) noexcept;

    /**  For column node_id  */
    ///Get the value of the column node_id, returns the default value if the column is null
    const int32_t &getValueOfNodeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getNodeId() const noexcept;
    ///Set the value of the column node_id
    void setNodeId(const int32_t &pNodeId) noexcept;

    /**  For column key_name  */
    ///Get the value of the column key_name, returns the default value if the column is null
    const std::string &getValueOfKeyName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getKeyName() const noexcept;
    ///Set the value of the column key_name
    void setKeyName(const std::string &pKeyName) noexcept;
    void setKeyName(std::string &&pKeyName) noexcept;

    /**  For column value_text  */
    ///Get the value of the column value_text, returns the default value if the column is null
    const std::string &getValueOfValueText() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getValueText() const noexcept;
    ///Set the value of the column value_text
    void setValueText(const std::string &pValueText) noexcept;
    void setValueText(std::string &&pValueText) noexcept;
    void setValueTextToNull() noexcept;

    /**  For column value_int  */
    ///Get the value of the column value_int, returns the default value if the column is null
    const int32_t &getValueOfValueInt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getValueInt() const noexcept;
    ///Set the value of the column value_int
    void setValueInt(const int32_t &pValueInt) noexcept;
    void setValueIntToNull() noexcept;

    /**  For column value_numeric  */
    ///Get the value of the column value_numeric, returns the default value if the column is null
    const std::string &getValueOfValueNumeric() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getValueNumeric() const noexcept;
    ///Set the value of the column value_numeric
    void setValueNumeric(const std::string &pValueNumeric) noexcept;
    void setValueNumeric(std::string &&pValueNumeric) noexcept;
    void setValueNumericToNull() noexcept;

    /**  For column value_boolean  */
    ///Get the value of the column value_boolean, returns the default value if the column is null
    const bool &getValueOfValueBoolean() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getValueBoolean() const noexcept;
    ///Set the value of the column value_boolean
    void setValueBoolean(const bool &pValueBoolean) noexcept;
    void setValueBooleanToNull() noexcept;

    /**  For column value_date  */
    ///Get the value of the column value_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfValueDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getValueDate() const noexcept;
    ///Set the value of the column value_date
    void setValueDate(const ::trantor::Date &pValueDate) noexcept;
    void setValueDateToNull() noexcept;

    /**  For column value_timestamp  */
    ///Get the value of the column value_timestamp, returns the default value if the column is null
    const ::trantor::Date &getValueOfValueTimestamp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getValueTimestamp() const noexcept;
    ///Set the value of the column value_timestamp
    void setValueTimestamp(const ::trantor::Date &pValueTimestamp) noexcept;
    void setValueTimestampToNull() noexcept;

    /**  For column value_json  */
    ///Get the value of the column value_json, returns the default value if the column is null
    const std::string &getValueOfValueJson() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getValueJson() const noexcept;
    ///Set the value of the column value_json
    void setValueJson(const std::string &pValueJson) noexcept;
    void setValueJson(std::string &&pValueJson) noexcept;
    void setValueJsonToNull() noexcept;

    /**  For column value_uuid  */
    ///Get the value of the column value_uuid, returns the default value if the column is null
    const std::string &getValueOfValueUuid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getValueUuid() const noexcept;
    ///Set the value of the column value_uuid
    void setValueUuid(const std::string &pValueUuid) noexcept;
    void setValueUuid(std::string &&pValueUuid) noexcept;
    void setValueUuidToNull() noexcept;

    /**  For column value_bytea  */
    ///Get the value of the column value_bytea, returns the default value if the column is null
    const std::vector<char> &getValueOfValueBytea() const noexcept;
    ///Return the column value by std::string with binary data
    std::string getValueOfValueByteaAsString() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::vector<char>> &getValueBytea() const noexcept;
    ///Set the value of the column value_bytea
    void setValueBytea(const std::vector<char> &pValueBytea) noexcept;
    void setValueBytea(const std::string &pValueBytea) noexcept;
    void setValueByteaToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 12;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<NodeMetadata>;
    friend drogon::orm::BaseBuilder<NodeMetadata, true, true>;
    friend drogon::orm::BaseBuilder<NodeMetadata, true, false>;
    friend drogon::orm::BaseBuilder<NodeMetadata, false, true>;
    friend drogon::orm::BaseBuilder<NodeMetadata, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<NodeMetadata>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> metadataId_;
    std::shared_ptr<int32_t> nodeId_;
    std::shared_ptr<std::string> keyName_;
    std::shared_ptr<std::string> valueText_;
    std::shared_ptr<int32_t> valueInt_;
    std::shared_ptr<std::string> valueNumeric_;
    std::shared_ptr<bool> valueBoolean_;
    std::shared_ptr<::trantor::Date> valueDate_;
    std::shared_ptr<::trantor::Date> valueTimestamp_;
    std::shared_ptr<std::string> valueJson_;
    std::shared_ptr<std::string> valueUuid_;
    std::shared_ptr<std::vector<char>> valueBytea_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[12]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where metadata_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where metadata_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "metadata_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "node_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "key_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "value_text,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "value_int,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "value_numeric,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "value_boolean,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "value_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "value_timestamp,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "value_json,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "value_uuid,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "value_bytea,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace myapp
} // namespace drogon_model
