/**
 *
 *  TreeNodes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TreeNodes.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::myapp;

const std::string TreeNodes::Cols::_node_id = "\"node_id\"";
const std::string TreeNodes::Cols::_parent_id = "\"parent_id\"";
const std::string TreeNodes::primaryKeyName = "node_id";
const bool TreeNodes::hasPrimaryKey = true;
const std::string TreeNodes::tableName = "\"tree_nodes\"";

const std::vector<typename TreeNodes::MetaData> TreeNodes::metaData_={
{"node_id","int32_t","integer",4,1,1,1},
{"parent_id","int32_t","integer",4,0,0,0}
};
const std::string &TreeNodes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TreeNodes::TreeNodes(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r["node_id"].as<int32_t>());
        }
        if(!r["parent_id"].isNull())
        {
            parentId_=std::make_shared<int32_t>(r["parent_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            parentId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

TreeNodes::TreeNodes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            parentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

TreeNodes::TreeNodes(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("parent_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["parent_id"].isNull())
        {
            parentId_=std::make_shared<int32_t>((int32_t)pJson["parent_id"].asInt64());
        }
    }
}

void TreeNodes::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            parentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void TreeNodes::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("node_id"))
    {
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("parent_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["parent_id"].isNull())
        {
            parentId_=std::make_shared<int32_t>((int32_t)pJson["parent_id"].asInt64());
        }
    }
}

const int32_t &TreeNodes::getValueOfNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nodeId_)
        return *nodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TreeNodes::getNodeId() const noexcept
{
    return nodeId_;
}
void TreeNodes::setNodeId(const int32_t &pNodeId) noexcept
{
    nodeId_ = std::make_shared<int32_t>(pNodeId);
    dirtyFlag_[0] = true;
}
const typename TreeNodes::PrimaryKeyType & TreeNodes::getPrimaryKey() const
{
    assert(nodeId_);
    return *nodeId_;
}

const int32_t &TreeNodes::getValueOfParentId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(parentId_)
        return *parentId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TreeNodes::getParentId() const noexcept
{
    return parentId_;
}
void TreeNodes::setParentId(const int32_t &pParentId) noexcept
{
    parentId_ = std::make_shared<int32_t>(pParentId);
    dirtyFlag_[1] = true;
}
void TreeNodes::setParentIdToNull() noexcept
{
    parentId_.reset();
    dirtyFlag_[1] = true;
}

void TreeNodes::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TreeNodes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "parent_id"
    };
    return inCols;
}

void TreeNodes::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getParentId())
        {
            binder << getValueOfParentId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TreeNodes::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void TreeNodes::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getParentId())
        {
            binder << getValueOfParentId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TreeNodes::toJson() const
{
    Json::Value ret;
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getParentId())
    {
        ret["parent_id"]=getValueOfParentId();
    }
    else
    {
        ret["parent_id"]=Json::Value();
    }
    return ret;
}

Json::Value TreeNodes::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getNodeId())
            {
                ret[pMasqueradingVector[0]]=getValueOfNodeId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getParentId())
            {
                ret[pMasqueradingVector[1]]=getValueOfParentId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getParentId())
    {
        ret["parent_id"]=getValueOfParentId();
    }
    else
    {
        ret["parent_id"]=Json::Value();
    }
    return ret;
}

bool TreeNodes::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(0, "node_id", pJson["node_id"], err, true))
            return false;
    }
    if(pJson.isMember("parent_id"))
    {
        if(!validJsonOfField(1, "parent_id", pJson["parent_id"], err, true))
            return false;
    }
    return true;
}
bool TreeNodes::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TreeNodes::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(0, "node_id", pJson["node_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("parent_id"))
    {
        if(!validJsonOfField(1, "parent_id", pJson["parent_id"], err, false))
            return false;
    }
    return true;
}
bool TreeNodes::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TreeNodes::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
