name: fastapi-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
      - fastapi
      - "uvicorn[standard]"
      - watchfiles
      - pydantic
      - httpx
      - sqlalchemy
